export const data = JSON.stringify([
	{
		id: 1,
		name: 'Driftwood',
		description: 'Sample candle description',
		price: 47,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 2,
		starRatingCount: 14,
		quantity: 8,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 2,
		name: 'Twisted Peppermint',
		description: 'Sample candle description',
		price: 83,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 4,
		starRatingCount: 21,
		quantity: 0,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 3,
		name: 'Spiced Apple Toddy',
		description: 'Sample candle description',
		price: 53,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 1,
		starRatingCount: 73,
		quantity: 89,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 4,
		name: 'Tiki Beach',
		description: 'Sample candle description',
		price: 93,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 2,
		starRatingCount: 85,
		quantity: 98,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 5,
		name: 'Lemon Mint Leaf',
		description: 'Sample candle description',
		price: 45,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 75,
		quantity: 3,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 6,
		name: 'Marshmallow Fireside',
		description: 'Sample candle description',
		price: 29,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 2,
		starRatingCount: 24,
		quantity: 41,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 7,
		name: 'Buttercream',
		description: 'Sample candle description',
		price: 2,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 1,
		quantity: 71,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 8,
		name: 'Cherry Blossom',
		description: 'Sample candle description',
		price: 83,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 2,
		starRatingCount: 47,
		quantity: 79,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 9,
		name: 'Rose Water & Ivy',
		description: 'Sample candle description',
		price: 66,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 1,
		quantity: 0,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 10,
		name: 'Orange Blossom',
		description: 'Sample candle description',
		price: 50,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 89,
		quantity: 4,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 11,
		name: 'Blueberry Scone',
		description: 'Sample candle description',
		price: 50,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 3,
		starRatingCount: 53,
		quantity: 26,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 12,
		name: 'Pink Petal Tea Cake',
		description: 'Sample candle description',
		price: 49,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 9,
		quantity: 64,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 13,
		name: 'Verbena Waters',
		description: 'Sample candle description',
		price: 16,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 3,
		starRatingCount: 70,
		quantity: 22,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 14,
		name: 'Pink Sands',
		description: 'Sample candle description',
		price: 61,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 26,
		quantity: 5,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 15,
		name: 'Lemon Verbena',
		description: 'Sample candle description',
		price: 63,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 22,
		quantity: 8,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 16,
		name: 'Fresh Strawberry Tart',
		description: 'Sample candle description',
		price: 8,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 4,
		starRatingCount: 67,
		quantity: 21,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 17,
		name: 'Vanilla Pumpkin Marshmallow',
		description: 'Sample candle description',
		price: 18,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 4,
		starRatingCount: 89,
		quantity: 26,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 18,
		name: 'Chocolate Layer Cake',
		description: 'Sample candle description',
		price: 53,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 3,
		starRatingCount: 73,
		quantity: 38,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 19,
		name: 'Napa Valley Sunset',
		description: 'Sample candle description',
		price: 52,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 4,
		starRatingCount: 70,
		quantity: 56,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 20,
		name: 'Sun-Drenched Apricot Rose',
		description: 'Sample candle description',
		price: 76,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 53,
		quantity: 70,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 21,
		name: 'Sparkling Icicles',
		description: 'Sample candle description',
		price: 22,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 3,
		starRatingCount: 0,
		quantity: 4,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 22,
		name: 'Red Velvet Cupcake',
		description: 'Sample candle description',
		price: 41,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 1,
		starRatingCount: 79,
		quantity: 24,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 23,
		name: 'Brown Sugar & Cinnamon',
		description: 'Sample candle description',
		price: 4,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 0,
		starRatingCount: 72,
		quantity: 37,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 24,
		name: 'Mango Peach Salsa',
		description: 'Sample candle description',
		price: 4,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 4,
		starRatingCount: 17,
		quantity: 78,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
	{
		id: 25,
		name: 'Blueberry Scone',
		description: 'Sample candle description',
		price: 30,
		imageUrl: 'https://via.placeholder.com/300x300',
		inventoryDate: '2023-12-31T08:00:00.000Z',
		starRating: 2,
		starRatingCount: 96,
		quantity: 78,
		inventoryStatus: 'InStock',
		dimensions: '3x3x5in',
		waxType: 'Cotton, Hemp',
		weight: '1.5lb',
		wickType: 'Lead-Free Cotton',
		burnTime: '30-35 hours',
		inWishlist: false,
		quantityInCart: 0,
	},
])
